---
name: CI
on: [push]
jobs:
  setup:
    name: SetUp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: yarn
      - name: 'Install'
        run: yarn install
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
  test:
    name: Test
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: yarn
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: 'Test'
        run: yarn test
  package:
    name: Package
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: yarn
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: 'Package'
        run: yarn package
  lint-ts:
    name: Lint TypeScript
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: yarn
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: 'Lint TypeScript'
        run: yarn lint:ts
  lint-css:
    name: Lint CSS
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
          cache: yarn
      - name: Restore node modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
      - name: 'Lint CSS'
        run: yarn lint:css
